"use client";
import dynamic from "next/dynamic";
import "./globals.css";
// import type { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const WalletConnectionProvider = dynamic(
  () => import("../context/WalletConnectionProvider"),
  { ssr: false },
);
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <WalletConnectionProvider>{children}</WalletConnectionProvider>
      </body>
    </html>
  );
}
